In [0]:
import tensorflow

In [2]:
tensorflow.__version__

'2.2.0-rc3'

In [0]:
import tensorflow_datasets as td
import tensorflow_hub as hub

In [4]:
td.list_builders()

['abstract_reasoning',
 'aeslc',
 'aflw2k3d',
 'amazon_us_reviews',
 'arc',
 'bair_robot_pushing_small',
 'beans',
 'big_patent',
 'bigearthnet',
 'billsum',
 'binarized_mnist',
 'binary_alpha_digits',
 'c4',
 'caltech101',
 'caltech_birds2010',
 'caltech_birds2011',
 'cars196',
 'cassava',
 'cats_vs_dogs',
 'celeb_a',
 'celeb_a_hq',
 'cfq',
 'chexpert',
 'cifar10',
 'cifar100',
 'cifar10_1',
 'cifar10_corrupted',
 'citrus_leaves',
 'cityscapes',
 'civil_comments',
 'clevr',
 'cmaterdb',
 'cnn_dailymail',
 'coco',
 'coil100',
 'colorectal_histology',
 'colorectal_histology_large',
 'cos_e',
 'curated_breast_imaging_ddsm',
 'cycle_gan',
 'deep_weeds',
 'definite_pronoun_resolution',
 'diabetic_retinopathy_detection',
 'div2k',
 'dmlab',
 'downsampled_imagenet',
 'dsprites',
 'dtd',
 'duke_ultrasound',
 'dummy_dataset_shared_generator',
 'dummy_mnist',
 'emnist',
 'eraser_multi_rc',
 'esnli',
 'eurosat',
 'fashion_mnist',
 'flic',
 'flores',
 'food101',
 'gap',
 'gigaword',
 'glue',
 'gr

## Using the validation data additionally with train,test data



In [0]:
train_data, validation_data, test_data = td.load(
    name="imdb_reviews", 
    split=('train[:60%]', 'train[60%:]', 'test'),
    as_supervised=True)

In [0]:
train_examples_batch, train_labels_batch = next(iter(train_data.batch(10)))

In [11]:
train_examples_batch

<tf.Tensor: shape=(10,), dtype=string, numpy=
array([b"This was an absolutely terrible movie. Don't be lured in by Christopher Walken or Michael Ironside. Both are great actors, but this must simply be their worst role in history. Even their great acting could not redeem this movie's ridiculous storyline. This movie is an early nineties US propaganda piece. The most pathetic scenes were those when the Columbian rebels were making their cases for revolutions. Maria Conchita Alonso appeared phony, and her pseudo-love affair with Walken was nothing but a pathetic emotional plug in a movie that was devoid of any real meaning. I am disappointed that there are movies like this, ruining actor's like Christopher Walken's good name. I could barely sit through it.",
       b'I have been known to fall asleep during films, but this is usually due to a combination of things including, really tired, being warm and comfortable on the sette and having just eaten a lot. However on this occasion I fell 

In [13]:
train_labels_batch

<tf.Tensor: shape=(10,), dtype=int64, numpy=array([0, 0, 0, 1, 1, 1, 0, 0, 0, 0])>

In [0]:
 pretrained_model = "https://tfhub.dev/google/tf2-preview/gnews-swivel-20dim/1"

In [0]:
hub_layer=hub.KerasLayer(pretrained_model,input_shape=[], dtype=tensorflow.string,trainable=True)

In [17]:
hub_layer(train_examples_batch[:2])

<tf.Tensor: shape=(2, 20), dtype=float32, numpy=
array([[ 1.765786  , -3.882232  ,  3.9134233 , -1.5557289 , -3.3362343 ,
        -1.7357955 , -1.9954445 ,  1.2989551 ,  5.081598  , -1.1041286 ,
        -2.0503852 , -0.72675157, -0.65675956,  0.24436149, -3.7208383 ,
         2.0954835 ,  2.2969332 , -2.0689783 , -2.9489717 , -1.1315987 ],
       [ 1.8804485 , -2.5852382 ,  3.4066997 ,  1.0982676 , -4.056685  ,
        -4.891284  , -2.785554  ,  1.3874227 ,  3.8476458 , -0.9256538 ,
        -1.896706  ,  1.2113281 ,  0.11474707,  0.76209456, -4.8791065 ,
         2.906149  ,  4.7087674 , -2.3652055 , -3.5015898 , -1.6390051 ]],
      dtype=float32)>

## Building the model

In [0]:
model=tensorflow.keras.Sequential()

In [19]:
model.add(hub_layer)#input layer(word2vec emneddings)
model.add(tensorflow.keras.layers.Dense(16,activation='relu'))
model.add(tensorflow.keras.layers.Dense(1,activation='sigmoid'))
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
keras_layer (KerasLayer)     (None, 20)                400020    
_________________________________________________________________
dense (Dense)                (None, 16)                336       
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 17        
Total params: 400,373
Trainable params: 400,373
Non-trainable params: 0
_________________________________________________________________


In [0]:
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [21]:
model.fit(train_data.shuffle(10000).batch(512),epochs=20,validation_data=validation_data.batch(512))

Epoch 1/20
30/30 [==============================] - 3s 106ms/step - loss: 1.0180 - accuracy: 0.5022 - val_loss: 0.8179 - val_accuracy: 0.5185
Epoch 2/20
30/30 [==============================] - 3s 105ms/step - loss: 0.7542 - accuracy: 0.5530 - val_loss: 0.7080 - val_accuracy: 0.5830
Epoch 3/20
30/30 [==============================] - 3s 101ms/step - loss: 0.6609 - accuracy: 0.6247 - val_loss: 0.6334 - val_accuracy: 0.6543
Epoch 4/20
30/30 [==============================] - 3s 99ms/step - loss: 0.5976 - accuracy: 0.6842 - val_loss: 0.5815 - val_accuracy: 0.7037
Epoch 5/20
30/30 [==============================] - 5s 165ms/step - loss: 0.5526 - accuracy: 0.7233 - val_loss: 0.5462 - val_accuracy: 0.7287
Epoch 6/20
30/30 [==============================] - 4s 141ms/step - loss: 0.5155 - accuracy: 0.7539 - val_loss: 0.5155 - val_accuracy: 0.7528
Epoch 7/20
30/30 [==============================] - 3s 107ms/step - loss: 0.4802 - accuracy: 0.7823 - val_loss: 0.4863 - val_accuracy: 0.7734
Epoch 8

In [22]:
model.predict(['It was a horrible movie'])

array([[0.13780037]], dtype=float32)

In [23]:
model.predict(['just splendid'])

array([[0.2664992]], dtype=float32)

In [24]:
model.predict(["This is the worst movie I have ever seen",
              "An excellent movie that I enjoyed a lot",
              "how can one make such a horrible movie? there is no story, acting direction everything is very poor"])

array([[0.20413354],
       [0.98883307],
       [0.02582903]], dtype=float32)

In [28]:
results=model.evaluate(test_data.batch(512),verbose=1)
for name,value in zip(model.metrics_names,results):
  print('{} : {:.2f}'.format(name,value))

49/49 [==============================] - 3s 68ms/step - loss: 0.3183 - accuracy: 0.8636
loss : 0.32
accuracy : 0.86
